swagger: '2.0'
info:
  description: >-
    Serviço destinado a realizar portabilidade de números VIVO para outras operadoras.
  
  version: 1.0.0
  title: VIVO Portabilidade
  contact:
    email: sysmap_ms@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: ms-src-portability
basePath: /v1
tags:
  - name: portability
    description: Gerencia os processos de potabilidade
    
schemes:
  - https
  - http
paths:
  /portability:
    post:
      tags:
        - portability
      summary: Cria um processo de portabilidade
      operationId: CreatePortability
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Informações necessarias para criar um processo de portabilidade
          required: true
          schema:
            $ref: '#/definitions/InputPortability'
      responses:
        '201':
          description: Processo de portabilidade criado com sucesso

  /portability/{portabilityId}:
    put:
      tags:
        - portability
      summary: Atualiza status da portabilidade
      operationId: PutStatus
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Status da portabilidade pós processamento
          required: true
          schema:
            $ref: '#/definitions/InputPutStatus'
        - in: path
          name: portabilityId
          type: string
          required: true
          description: Id da portabilidade
      responses:
        '200':
          description: Status da portabilidade atualizado com sucesso

definitions:
  InputPortability:
    type: object
    properties:
      portability:
        $ref: '#/definitions/PortabilityResume'
      user:
        $ref: '#/definitions/User'

  PortabilityResume:
    type: object
    properties:
      source:
        type: string
        enum:
          - VIVO
          - CLARO
          - NEXTEL
          - TIM
          - OI
      target:
        type: string
        enum:
          - VIVO
          - CLARO
          - NEXTEL
          - TIM
          - OI
          
  User:
    type: object
    properties:
      line:
        $ref: '#/definitions/LineInformation'
      address:
        $ref: '#/definitions/Address'
      name:
        type: string
        format: int64
      dateOfBirth:
        type: string
        pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
        example: "YYYY-MM-DD"
      documentNumber:
        type: string
        format: int64
  
  LineInformation:
    type: object
    properties:
      number:
        type: string
  
  Address:
    type: object
    properties:
      street:
        type: string
      number:
        type: string
      city:
        type: string
      country:
        type: string
      stateOrRegion:
        type: string
        
  InputPutStatus:
    type: object
    properties:
      status:
        enum:
          - PORTED
          - UNPORTED
          - PROCESSING_PORTABILITY
